query ListarProductores @auth(level: PUBLIC, insecureReason: "Demo public access") {
  producers {
    id
    fullName
    contactEmail
    bankAccount
  }
}

query ListarProductos @auth(level: PUBLIC, insecureReason: "Demo public access") {
  digitalProducts {
    id
    title
    format
    niche
    basePrice
    affiliateCommission
    producer {
      id
      fullName
      contactEmail
    }
  }
}
