type ProveedorAsociado @table {
  id: UUID! @default(expr: "uuidV4()")
  razonSocial: String!
  tipoSocio: String!
  emailContacto: String!
}

type BeneficioCatalogo @table {
  id: UUID! @default(expr: "uuidV4()")
  nombreBeneficio: String!
  categoria: String!
  valorEconomico: Float!
  costoPuntosGamificacion: Int!
  proveedor: ProveedorAsociado!
}
